export const IS_PROCESSING = "IS_PROCESSING";
export const IS_LOGIN_SUCCESS = "IS_LOGIN_SUCCESS";
export const IS_LOGIN_FAILED = "IS_LOGIN_FAILED";
export const IS_SIGNUP_SUCCESS = "IS_SIGNUP_SUCCESS";
export const IS_SIGNUP_FAILED = "IS_SIGNUP_FAILED";